apiVersion: v1
kind: Service
metadata:
  name: taskflow-app
  namespace: taskflow
spec:
  type: NodePort
  selector:
    app: taskflow-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30080             # akses via http://<minikube-ip>:30080
