apiVersion: v1
kind: Secret
metadata:
  name: taskflow-secret
  namespace: taskflow
type: Opaque
stringData:
  mysql-root-password: "rootpassword"
  mysql-password: "taskflow123"
  secret-key: "prod-secret-ganti-ini-dengan-string-acak"
  telegram-bot-token: ""          # isi setelah setup bot Telegram
